name: build hatch

on:
  push:
    tags:
    - hatch-v*

concurrency:
  group: build-hatch-${{ github.head_ref }}

env:
  STABLE_PYTHON_VERSION: '3.11'

jobs:
  build:
    name: Build wheels and source distribution
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Install build dependencies
      run: python -m pip install --upgrade build

    - name: Build source distribution
      run: python -m build

    - uses: actions/upload-artifact@v3
      with:
        name: artifacts
        path: dist/*
        if-no-files-found: error

  publish:
    name: Publish release
    needs:
    - build
    runs-on: ubuntu-latest

    steps:
    - uses: actions/download-artifact@v3
      with:
        name: artifacts
        path: dist

    - name: Push build artifacts to PyPI
      uses: pypa/gh-action-pypi-publish@v1.8.5
      with:
        skip_existing: true
        user: __token__
        password: ${{ secrets.PYPI_API_TOKEN_HATCH }}

  build-zipapp:
    name: Build zipapp
    needs:
    - build
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Set up Python ${{ env.STABLE_PYTHON_VERSION }}
      uses: actions/setup-python@v4
      with:
        python-version: ${{ env.STABLE_PYTHON_VERSION }}

    - name: Upgrade pip, Install shiv
      run: |
        python -m pip install --upgrade pip
        pip install shiv

    - name: Build zipapp
      run: shiv -c hatch -o ./hatch.pyz .

    - name: Test zipapp
      run: python ./hatch.pyz --version

    - name: Upload to releases
      uses: softprops/action-gh-release@v1
      with:
        files: hatch.pyz
